version: "3.8"

services:
  web:
    image: jitsi/web:stable
    restart: unless-stopped
    environment:
      - PUBLIC_URL=jmeet.streamafrica.cloud
      - TZ=Africa/Accra
      - ENABLE_LETSENCRYPT=0
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
    depends_on:
      - prosody
      - jicofo
      - jvb

  prosody:
    image: jitsi/prosody:stable
    restart: unless-stopped
    environment:
      - TZ=Africa/Accra
      - XMPP_DOMAIN=meet.jitsi
      - XMPP_AUTH_DOMAIN=auth.meet.jitsi
      - XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
      - JICOFO_COMPONENT_SECRET=your-jicofo-secret
      - JVB_AUTH_PASSWORD=your-jvb-secret
      - JICOFO_AUTH_PASSWORD=your-jicofo-secret

  jicofo:
    image: jitsi/jicofo:stable
    restart: unless-stopped
    environment:
      - TZ=Africa/Accra
      - XMPP_DOMAIN=meet.jitsi
      - JICOFO_AUTH_PASSWORD=your-jicofo-secret

  jvb:
    image: jitsi/jvb:stable
    restart: unless-stopped
    ports:
      - "10000:10000/udp"
    environment:
      - TZ=Africa/Accra
      - DOCKER_HOST_ADDRESS=YOUR_PUBLIC_IP
      - JVB_AUTH_PASSWORD=your-jvb-secret
